spring.application.name=PlanesDeVuelos
server.port= 8083

spring.profiles.include=secrets


spring.threads.virtual.enabled=true


spring.mvc.problemdetails.enabled=false


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


spring.jackson.serialization.fail-on-empty-beans=true



spring.datasource.url=jdbc:postgresql://ep-little-union-apnb65hm-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6Xbig9rjOlZQ
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2


